### PR TITLE
Fix notices for resources base or block cost not set closes #14

### LINKED ISSUE #14: Lots of warnings and errors on import
Trying to import this gave me all kinds of nasty errors:
https://bookingsdemo.blog/wp-content/uploads/2019/07/bookings-demos-yoga-class.zip from
https://bookingsdemo.blog/product/yoga-class/

Bookings Helper 1.0.2
WordPress 5.4
WooCommerce Bookings 1.15.15
WooCommerce Min/Max Quantities 2.4.15
WooCommerce Smart Coupons  4.7.1
WooCommerce  4.0.1
```
Notice: Undefined index: gcal_event_id in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 489

Notice: Undefined index: title in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 490

Notice: Undefined index: range_type in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 491

Notice: Undefined index: from_date in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 492

Notice: Undefined index: to_date in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 493

Notice: Undefined index: from_range in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 494

Notice: Undefined index: to_range in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 495

Notice: Undefined index: bookable in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 496

Notice: Undefined index: priority in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 497

Notice: Undefined index: ordering in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 498

Notice: Undefined index: date_created in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 499

Notice: Undefined index: date_modified in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 500

Notice: Undefined index: rrule in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 501

Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.0.) in D:\laragon\www\my-site\wp-includes\functions.php on line 5167

WordPress database error: [Column 'gcal_event_id' cannot be null]
INSERT INTO `wp_wc_bookings_availability` (`gcal_event_id`, `title`, `range_type`, `from_date`, `to_date`, `from_range`, `to_range`, `bookable`, `priority`, `ordering`, `date_created`, `date_modified`, `rrule`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

Notice: Undefined index: gcal_event_id in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 489

Notice: Undefined index: title in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 490

Notice: Undefined index: range_type in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 491

Notice: Undefined index: from_date in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 492

Notice: Undefined index: to_date in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 493

Notice: Undefined index: from_range in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 494

Notice: Undefined index: to_range in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 495

Notice: Undefined index: bookable in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 496

Notice: Undefined index: priority in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 497

Notice: Undefined index: ordering in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 498

Notice: Undefined index: date_created in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 499

Notice: Undefined index: date_modified in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 500

Notice: Undefined index: rrule in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 501

Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.0.) in D:\laragon\www\my-site\wp-includes\functions.php on line 5167

WordPress database error: [Column 'gcal_event_id' cannot be null]
INSERT INTO `wp_wc_bookings_availability` (`gcal_event_id`, `title`, `range_type`, `from_date`, `to_date`, `from_range`, `to_range`, `bookable`, `priority`, `ordering`, `date_created`, `date_modified`, `rrule`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

Notice: Undefined index: gcal_event_id in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 489

Notice: Undefined index: title in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 490

Notice: Undefined index: range_type in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 491

Notice: Undefined index: from_date in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 492

Notice: Undefined index: to_date in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 493

Notice: Undefined index: from_range in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 494

Notice: Undefined index: to_range in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 495

Notice: Undefined index: bookable in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 496

Notice: Undefined index: priority in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 497

Notice: Undefined index: ordering in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 498

Notice: Undefined index: date_created in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 499

Notice: Undefined index: date_modified in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 500

Notice: Undefined index: rrule in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 501

Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.0.) in D:\laragon\www\my-site\wp-includes\functions.php on line 5167

WordPress database error: [Column 'gcal_event_id' cannot be null]
INSERT INTO `wp_wc_bookings_availability` (`gcal_event_id`, `title`, `range_type`, `from_date`, `to_date`, `from_range`, `to_range`, `bookable`, `priority`, `ordering`, `date_created`, `date_modified`, `rrule`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

Notice: Undefined index: gcal_event_id in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 489

Notice: Undefined index: title in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 490

Notice: Undefined index: range_type in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 491

Notice: Undefined index: from_date in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 492

Notice: Undefined index: to_date in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 493

Notice: Undefined index: from_range in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 494

Notice: Undefined index: to_range in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 495

Notice: Undefined index: bookable in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 496

Notice: Undefined index: priority in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 497

Notice: Undefined index: ordering in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 498

Notice: Undefined index: date_created in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 499

Notice: Undefined index: date_modified in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 500

Notice: Undefined index: rrule in D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php on line 501

Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.0.) in D:\laragon\www\my-site\wp-includes\functions.php on line 5167

WordPress database error: [Column 'gcal_event_id' cannot be null]
INSERT INTO `wp_wc_bookings_availability` (`gcal_event_id`, `title`, `range_type`, `from_date`, `to_date`, `from_range`, `to_range`, `bookable`, `priority`, `ordering`, `date_created`, `date_modified`, `rrule`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

Warning: Cannot modify header information - headers already sent by (output started at D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php:494) in D:\laragon\www\my-site\wp-includes\functions.php on line 6221

Warning: Cannot modify header information - headers already sent by (output started at D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php:494) in D:\laragon\www\my-site\wp-admin\includes\misc.php on line 1259

Warning: Cannot modify header information - headers already sent by (output started at D:\laragon\www\my-site\wp-content\plugins\bookings-helper-master\bookings-helper.php:494) in D:\laragon\www\my-site\wp-admin\admin-header.php on line 9
```

### PR DESCRIPTION
**Pull request by roykho**
Fixes #14 

* Fix - Notices when importing products with resources and no set block/base costs.

Testing steps:
* Go to the tools->bookings helper
* Import a product with bookings resources with no base/block cost.
* After import make sure there are no PHP notices.

### CODE REVIEW

File: bookings-helper.php [hunk 1]
```diff
@@ -689,8 +689,8 @@ public function import_product() {
 							$wpdb->query( $wpdb->prepare( "INSERT INTO {$wpdb->postmeta} ( post_id, meta_key, meta_value ) VALUES ( %d, %s, %s )", $resource_id, sanitize_text_field( $meta['meta_key'] ), sanitize_text_field( $meta['meta_value'] ) ) );		
 						}
 
-						$new_resource_base_costs[ $resource_id ]  = $resource_base_costs[ $resource['resource']['ID'] ];
-						$new_resource_block_costs[ $resource_id ] = $resource_block_costs[ $resource['resource']['ID'] ];
+						$new_resource_base_costs[ $resource_id ]  = ! empty( $resource_base_costs ) ? $resource_base_costs[ $resource['resource']['ID'] ] : '';
+						$new_resource_block_costs[ $resource_id ] = ! empty( $resource_block_costs ) ? $resource_block_costs[ $resource['resource']['ID'] ] : '';
```
Comment (bor0) [inline bookings-helper.php:694]:
```suggestion
						$new_resource_base_costs[ $resource_id ]  = ! empty( $resource_base_costs[ $resource['resource']['ID'] ] ) ? $resource_base_costs[ $resource['resource']['ID'] ] : '';
						$new_resource_block_costs[ $resource_id ] = ! empty( $resource_block_costs[ $resource['resource']['ID'] ] ) ? $resource_block_costs[ $resource['resource']['ID'] ] : '';
```
